### ISSUE TITLE
Move todos to issues.

### ISSUE THREAD

**Issue by dblodgett-usgs** [aaraney/NWM-Docker-Ensemble-Framework#2]
https://github.com/aaraney/PBenJ/blob/53f4ae3c5c364a8e972d05a9903a4126033b4d43/framework_dev/perturb_py_dev/Parameter_editor.py#L69

It's going to be easier to keep track of things that need to get done if you track them in issues and close them with commits.

**Comment by mandli** [comment]
Agreed.  Although I sometime do this it is more of a reminder to submit these as issues as soon as I can.
